/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as AuthenticatedOpsIndexRouteImport } from './routes/_authenticated/ops/index'
import { Route as AuthenticatedOpsAppNameRouteImport } from './routes/_authenticated/ops/$appName'
import { Route as AuthenticatedProcessesIndexRouteImport } from './routes/_authenticated/processes/index'
import { Route as AuthenticatedProcessesIdRouteImport } from './routes/_authenticated/processes/$id'
import { Route as ApiAlertingSettingsRouteImport } from './routes/api/alerting.settings'
import { Route as ApiAlertingTestRouteImport } from './routes/api/alerting.test'
import { Route as ApiOpsConfigRouteImport } from './routes/api/ops/config'
import { Route as ApiSettingsGeneralRouteImport } from './routes/api/settings.general'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOpsIndexRoute = AuthenticatedOpsIndexRouteImport.update({
  id: '/ops/',
  path: '/ops/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOpsAppNameRoute = AuthenticatedOpsAppNameRouteImport.update({
  id: '/ops/$appName',
  path: '/ops/$appName',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProcessesIndexRoute =
  AuthenticatedProcessesIndexRouteImport.update({
    id: '/processes/',
    path: '/processes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProcessesIdRoute =
  AuthenticatedProcessesIdRouteImport.update({
    id: '/processes/$id',
    path: '/processes/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAlertingSettingsRoute = ApiAlertingSettingsRouteImport.update({
  id: '/api/alerting/settings',
  path: '/api/alerting/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertingTestRoute = ApiAlertingTestRouteImport.update({
  id: '/api/alerting/test',
  path: '/api/alerting/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsConfigRoute = ApiOpsConfigRouteImport.update({
  id: '/api/ops/config',
  path: '/api/ops/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsGeneralRoute = ApiSettingsGeneralRouteImport.update({
  id: '/api/settings/general',
  path: '/api/settings/general',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/events': typeof ApiEventsRoute
  '/ops/$appName': typeof AuthenticatedOpsAppNameRoute
  '/processes/$id': typeof AuthenticatedProcessesIdRoute
  '/api/alerting/settings': typeof ApiAlertingSettingsRoute
  '/api/alerting/test': typeof ApiAlertingTestRoute
  '/api/ops/config': typeof ApiOpsConfigRoute
  '/api/settings/general': typeof ApiSettingsGeneralRoute
  '/ops/': typeof AuthenticatedOpsIndexRoute
  '/processes/': typeof AuthenticatedProcessesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/events': typeof ApiEventsRoute
  '/ops/$appName': typeof AuthenticatedOpsAppNameRoute
  '/processes/$id': typeof AuthenticatedProcessesIdRoute
  '/api/alerting/settings': typeof ApiAlertingSettingsRoute
  '/api/alerting/test': typeof ApiAlertingTestRoute
  '/api/ops/config': typeof ApiOpsConfigRoute
  '/api/settings/general': typeof ApiSettingsGeneralRoute
  '/ops': typeof AuthenticatedOpsIndexRoute
  '/processes': typeof AuthenticatedProcessesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/events': typeof ApiEventsRoute
  '/_authenticated/ops/$appName': typeof AuthenticatedOpsAppNameRoute
  '/_authenticated/processes/$id': typeof AuthenticatedProcessesIdRoute
  '/api/alerting/settings': typeof ApiAlertingSettingsRoute
  '/api/alerting/test': typeof ApiAlertingTestRoute
  '/api/ops/config': typeof ApiOpsConfigRoute
  '/api/settings/general': typeof ApiSettingsGeneralRoute
  '/_authenticated/ops/': typeof AuthenticatedOpsIndexRoute
  '/_authenticated/processes/': typeof AuthenticatedProcessesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/api/events'
    | '/ops/$appName'
    | '/processes/$id'
    | '/api/alerting/settings'
    | '/api/alerting/test'
    | '/api/ops/config'
    | '/api/settings/general'
    | '/ops/'
    | '/processes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/api/events'
    | '/ops/$appName'
    | '/processes/$id'
    | '/api/alerting/settings'
    | '/api/alerting/test'
    | '/api/ops/config'
    | '/api/settings/general'
    | '/ops'
    | '/processes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/api/events'
    | '/_authenticated/ops/$appName'
    | '/_authenticated/processes/$id'
    | '/api/alerting/settings'
    | '/api/alerting/test'
    | '/api/ops/config'
    | '/api/settings/general'
    | '/_authenticated/ops/'
    | '/_authenticated/processes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiAlertingSettingsRoute: typeof ApiAlertingSettingsRoute
  ApiAlertingTestRoute: typeof ApiAlertingTestRoute
  ApiOpsConfigRoute: typeof ApiOpsConfigRoute
  ApiSettingsGeneralRoute: typeof ApiSettingsGeneralRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ops/': {
      id: '/_authenticated/ops/'
      path: '/ops'
      fullPath: '/ops/'
      preLoaderRoute: typeof AuthenticatedOpsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ops/$appName': {
      id: '/_authenticated/ops/$appName'
      path: '/ops/$appName'
      fullPath: '/ops/$appName'
      preLoaderRoute: typeof AuthenticatedOpsAppNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/processes/': {
      id: '/_authenticated/processes/'
      path: '/processes'
      fullPath: '/processes/'
      preLoaderRoute: typeof AuthenticatedProcessesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/processes/$id': {
      id: '/_authenticated/processes/$id'
      path: '/processes/$id'
      fullPath: '/processes/$id'
      preLoaderRoute: typeof AuthenticatedProcessesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/alerting/settings': {
      id: '/api/alerting/settings'
      path: '/api/alerting/settings'
      fullPath: '/api/alerting/settings'
      preLoaderRoute: typeof ApiAlertingSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerting/test': {
      id: '/api/alerting/test'
      path: '/api/alerting/test'
      fullPath: '/api/alerting/test'
      preLoaderRoute: typeof ApiAlertingTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/config': {
      id: '/api/ops/config'
      path: '/api/ops/config'
      fullPath: '/api/ops/config'
      preLoaderRoute: typeof ApiOpsConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/general': {
      id: '/api/settings/general'
      path: '/api/settings/general'
      fullPath: '/api/settings/general'
      preLoaderRoute: typeof ApiSettingsGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedOpsAppNameRoute: typeof AuthenticatedOpsAppNameRoute
  AuthenticatedProcessesIdRoute: typeof AuthenticatedProcessesIdRoute
  AuthenticatedOpsIndexRoute: typeof AuthenticatedOpsIndexRoute
  AuthenticatedProcessesIndexRoute: typeof AuthenticatedProcessesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedOpsAppNameRoute: AuthenticatedOpsAppNameRoute,
  AuthenticatedProcessesIdRoute: AuthenticatedProcessesIdRoute,
  AuthenticatedOpsIndexRoute: AuthenticatedOpsIndexRoute,
  AuthenticatedProcessesIndexRoute: AuthenticatedProcessesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiAlertingSettingsRoute: ApiAlertingSettingsRoute,
  ApiAlertingTestRoute: ApiAlertingTestRoute,
  ApiOpsConfigRoute: ApiOpsConfigRoute,
  ApiSettingsGeneralRoute: ApiSettingsGeneralRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
